services:
  - type: web
    name: dinespace-api
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
  - type: web
    name: dinespace-client
    runtime: docker
    dockerfilePath: ./DineSpace/client/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://dinespace-api.onrender.com
